USE [SUPERSTORE]
GO
SELECT [DISCOUNT]
      ,[CUSTOMER_ID]
      ,[SHIP_MODE]
      ,[CUSTOMER_SEGMENT]
      ,[PRODUCT_CATEGORY]
      ,[PRODUCT_SUB_CATEGORY]
      ,[PRODUCT_NAME]
      ,[REGION]
      ,[ORDER_DATE]
      ,[SHIP_DATE]
      ,[PROFIT]
      ,[QUANTITY_ORDERED_NEW]
      ,[SALES]
      ,[ORDER_ID]
  FROM [dbo].[SuperStoreUS-2015]

--RETRIEVE THE TOTAL NUMBER OF ORDERS
SELECT COUNT (ORDER_ID) AS TOTAL_NUMBER_OF_ORDERS
FROM dbo.[SuperStoreUS-2015]

--RETRIEVE THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT ( DISTINCT CUSTOMER_ID) AS TOTAL_NUMBER_OF_CUSTOMERS
FROM dbo.[SuperStoreUS-2015]

--RETRIEVE THE TOTAL NUMBER OF PRODUCTS
SELECT COUNT ( DISTINCT PRODUCT_NAME) AS TOTAL_NUMBER_OF_PRODUCTS
FROM dbo.[SuperStoreUS-2015]

--CALCULATING TOTAL NUMBER OF SALES, AVARAGE DISCOUNT AND PROFIT
SELECT PRODUCT_CATEGORY,
SUM (SALES) AS TOTAL_SALES,
AVG (DISCOUNT) AS AVERAGE_DISCOUNT,
SUM (PROFIT) AS TOTAL_PROFIT
FROM dbo.[SuperStoreUS-2015]
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL_SALES DESC

--IDENTIFYING THE TOP 10 CUSTOMERS WITH THE HIGHEST TOTAL SALES
SELECT TOP 10 CUSTOMER_ID, SUM (Sales) AS TOTAL_SALES
FROM dbo.[SuperStoreUS-2015]
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SALES DESC;

--CALCULATING THE AVERAGE ORDER VALUE FOR EACH CUSTOMER SEGMENT 
SELECT CUSTOMER_SEGMENT, AVG (SALES) AS AVERAGE_ORDER_VALUE
FROM dbo.[SuperStoreUS-2015]
GROUP BY CUSTOMER_SEGMENT
ORDER BY AVERAGE_ORDER_VALUE DESC;

--ANALYZING MONTHLY SALES TO IDENTIFY THE MONTH WITH THE HIGHEST SALES
SELECT YEAR(ORDER_DATE) AS YEAR, MONTH(ORDER_DATE) AS MONTH, SUM (SALES) AS MONTHLY_SALES
FROM dbo.[SuperStoreUS-2015]
GROUP BY YEAR(ORDER_DATE), MONTH(ORDER_DATE)
ORDER BY MONTHLY_SALES DESC

--IDENTIFYING THE TOP 5 BEST SELLING PRODUCTS BASED ON TOTAL QUANTITY SOLD
SELECT TOP 5 PRODUCT_NAME, SUM (QUANTITY_ORDERED_NEW) AS TOTAL_QUANTITY_SOLD
FROM dbo.[SuperStoreUS-2015]
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC

--CALCULATING THE PROFIT MAGIN FOR EACH CUSTOMER SEGMENT
SELECT CUSTOMER_SEGMENT, AVG (PROFIT / SALES) * 100 AS PROFIT_MARGIN
FROM dbo.[SuperStoreUS-2015]
GROUP BY CUSTOMER_SEGMENT

--CALCULATING THE AVERAGE DISCOUNT FOR EACH PRODUCT CATEGORY AND ANALYZING THE IMPACT OF DISCOUNT ON SALES AND PROFIT
SELECT PRODUCT_CATEGORY,
AVG (DISCOUNT) AS AVERAGE_DISCOUNT,
AVG (SALES) AS AVERAGE_SALES,
AVG (PROFIT) AS AVERAGE_PROFIT
FROM dbo.[SuperStoreUS-2015]
GROUP BY PRODUCT_CATEGORY
ORDER BY AVERAGE_DISCOUNT DESC
